/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomOwnerDashboardRouteImport } from './routes/room-owner/dashboard'
import { Route as RoomOwnerAddListingRouteImport } from './routes/room-owner/add-listing'
import { Route as RoomOwnerEditListingIdRouteImport } from './routes/room-owner/edit-listing.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomOwnerDashboardRoute = RoomOwnerDashboardRouteImport.update({
  id: '/room-owner/dashboard',
  path: '/room-owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomOwnerAddListingRoute = RoomOwnerAddListingRouteImport.update({
  id: '/room-owner/add-listing',
  path: '/room-owner/add-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomOwnerEditListingIdRoute = RoomOwnerEditListingIdRouteImport.update({
  id: '/room-owner/edit-listing/$id',
  path: '/room-owner/edit-listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/room-owner/add-listing': typeof RoomOwnerAddListingRoute
  '/room-owner/dashboard': typeof RoomOwnerDashboardRoute
  '/room-owner/edit-listing/$id': typeof RoomOwnerEditListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/room-owner/add-listing': typeof RoomOwnerAddListingRoute
  '/room-owner/dashboard': typeof RoomOwnerDashboardRoute
  '/room-owner/edit-listing/$id': typeof RoomOwnerEditListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/room-owner/add-listing': typeof RoomOwnerAddListingRoute
  '/room-owner/dashboard': typeof RoomOwnerDashboardRoute
  '/room-owner/edit-listing/$id': typeof RoomOwnerEditListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/room-owner/add-listing'
    | '/room-owner/dashboard'
    | '/room-owner/edit-listing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/room-owner/add-listing'
    | '/room-owner/dashboard'
    | '/room-owner/edit-listing/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/room-owner/add-listing'
    | '/room-owner/dashboard'
    | '/room-owner/edit-listing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  RoomOwnerAddListingRoute: typeof RoomOwnerAddListingRoute
  RoomOwnerDashboardRoute: typeof RoomOwnerDashboardRoute
  RoomOwnerEditListingIdRoute: typeof RoomOwnerEditListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-owner/dashboard': {
      id: '/room-owner/dashboard'
      path: '/room-owner/dashboard'
      fullPath: '/room-owner/dashboard'
      preLoaderRoute: typeof RoomOwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-owner/add-listing': {
      id: '/room-owner/add-listing'
      path: '/room-owner/add-listing'
      fullPath: '/room-owner/add-listing'
      preLoaderRoute: typeof RoomOwnerAddListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-owner/edit-listing/$id': {
      id: '/room-owner/edit-listing/$id'
      path: '/room-owner/edit-listing/$id'
      fullPath: '/room-owner/edit-listing/$id'
      preLoaderRoute: typeof RoomOwnerEditListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  RoomOwnerAddListingRoute: RoomOwnerAddListingRoute,
  RoomOwnerDashboardRoute: RoomOwnerDashboardRoute,
  RoomOwnerEditListingIdRoute: RoomOwnerEditListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
